[package]
name = "weavelang"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
pest = "2.7"
pest_derive = "2.7"
gdnative = "0.11.0"
rand = "0.8.5"

[profile.release]
opt-level = 3
lto = "thin"