[package]
name = "weavelang"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
pest = "2.7"
pest_derive = "2.7"
godot = { git = "https://github.com/godot-rust/gdextension", tag = "0.1.3" }

[profile.release]
opt-level = 3
lto = "thin"