[package]
name = "weavelang"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
pest = "2.1.3"
pest_derive = "2.1.0"
rand = "0.8.5"

# This is the correct crate name and version for GDNative (Godot 3.x).
gdnative = "0.11.0"
godot = "0.3.4"
